name: assignment1
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _python_abi3_support=1.0
  - anaconda-anon-usage=0.7.5
  - anaconda-auth=0.12.3
  - anaconda-cli-base=0.7.0
  - annotated-types=0.6.0
  - archspec=0.2.5
  - asttokens=3.0.1
  - boltons=25.0.0
  - brotlicffi=1.2.0.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2026.1.4
  - certifi=2026.01.04
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click=8.2.1
  - comm=0.2.3
  - conda=26.1.0
  - conda-anaconda-telemetry=0.3.0
  - conda-anaconda-tos=0.2.2
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=25.11.0
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.12.0
  - cpp-expected=1.1.0
  - cpython=3.13.12
  - cryptography=46.0.3
  - dbus=1.16.2
  - debugpy=1.8.20
  - decorator=5.2.1
  - distro=1.9.0
  - executing=2.2.1
  - expat=2.7.3
  - fmt=11.2.0
  - frozendict=2.4.6
  - gettext=0.21.0
  - icu=73.1
  - idna=3.11
  - ipykernel=7.1.0
  - ipython=9.10.0
  - ipython_pygments_lexers=1.1.1
  - jansson=2.14
  - jaraco.classes=3.4.0
  - jaraco.context=6.0.0
  - jaraco.functools=4.1.0
  - jedi=0.19.2
  - jeepney=0.7.1
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - jupyter_client=8.8.0
  - jupyter_core=5.9.1
  - keyring=25.7.0
  - keyutils=1.6.3
  - krb5=1.21.3
  - ld_impl_linux-64=2.44
  - libarchive=3.8.2
  - libcurl=8.16.0
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libiconv=1.16
  - libidn2=2.3.8
  - libkrb5=1.21.3
  - libmamba=2.3.2
  - libmambapy=2.3.2
  - libmpdec=4.0.0
  - libnghttp2=1.67.1
  - libsodium=1.0.20
  - libsolv=0.7.30
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libunistring=1.3
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lmdb=0.9.31
  - lz4-c=1.9.4
  - markdown-it-py=4.0.0
  - matplotlib-inline=0.2.1
  - mdurl=0.1.2
  - menuinst=2.4.2
  - more-itertools=10.8.0
  - msgpack-python=1.1.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nlohmann_json=3.11.2
  - openssl=3.6.1
  - packaging=25.0
  - parso=0.8.5
  - pcre2=10.46
  - pexpect=4.9.0
  - pip=25.3
  - pkce=1.0.3
  - platformdirs=4.5.0
  - pluggy=1.5.0
  - prompt-toolkit=3.0.52
  - psutil=7.2.2
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pybind11-abi=5
  - pycosat=0.6.6
  - pycparser=2.23
  - pydantic=2.12.4
  - pydantic-core=2.41.5
  - pydantic-settings=2.12.0
  - pygments=2.19.2
  - pyjwt=2.10.1
  - pysocks=1.7.1
  - python=3.13.11
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.1.0
  - python-gil=3.13.12
  - python_abi=3.13
  - pyzmq=27.1.0
  - readchar=4.2.1
  - readline=8.3
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.5
  - rich=14.2.0
  - ruamel.yaml=0.18.16
  - ruamel.yaml.clib=0.2.14
  - secretstorage=3.4.0
  - semver=3.0.4
  - setuptools=80.9.0
  - shellingham=1.5.4
  - simdjson=3.10.1
  - six=1.17.0
  - sqlite=3.51.0
  - stack_data=0.6.3
  - tk=8.6.15
  - tomli=2.2.1
  - tornado=6.5.4
  - tqdm=4.67.1
  - traitlets=5.14.3
  - truststore=0.10.1
  - typer=0.20.0
  - typer-slim=0.20.0
  - typer-slim-standard=0.20.0
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.6.1
  - wcwidth=0.5.3
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml-cpp=0.8.0
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstandard=0.24.0
  - zstd=1.5.7
  - pip:
      - asttokens==3.0.1
      - attrs==25.4.0
      - choreographer==1.2.1
      - comm==0.2.3
      - contourpy==1.3.3
      - cycler==0.12.1
      - debugpy==1.8.20
      - decorator==5.2.1
      - duckdb==1.4.4
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - fonttools==4.61.1
      - iniconfig==2.3.0
      - ipykernel==7.1.0
      - ipython==9.10.0
      - ipython_pygments_lexers==1.1.1
      - jedi==0.19.2
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - jupyter_client==8.8.0
      - jupyter_core==5.9.1
      - kaleido==1.2.0
      - kiwisolver==1.4.9
      - logistro==2.0.1
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - narwhals==2.16.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - numpy==2.4.2
      - orjson==3.11.7
      - packaging==26.0
      - pandas==3.0.0
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==12.1.0
      - platformdirs==4.5.1
      - plotly==6.5.2
      - pluggy==1.6.0
      - prompt_toolkit==3.0.52
      - psutil==7.2.2
      - ptyprocess==0.7.0
      - pure_eval==0.2.3
      - Pygments==2.19.2
      - pyparsing==3.3.2
      - pytest==9.0.2
      - pytest-timeout==2.4.0
      - python-dateutil==2.9.0.post0
      - pyzmq==27.1.0
      - referencing==0.37.0
      - rpds-py==0.30.0
      - seaborn==0.13.2
      - simplejson==3.20.2
      - six==1.17.0
      - stack-data==0.6.3
      - streamlit==1.40.2
      - tornado==6.5.4
      - traitlets==5.14.3
      - typing_extensions==4.15.0
      - wcwidth==0.5.3
prefix: /home/fredc/miniconda3/envs/assignment1
